### ISSUE TITLE
error Received malformed response from registry for "zoe". The registry may be down.

### ISSUE THREAD

**Issue by Albertobar94** [Hendrixer/production-grade-nextjs#2]
it seems that this library has been taken down.

**Comment by Yansb** [comment]
You can delete zoe from the devDependencies object in `package.json` and delete the import on `.eslintrc`
worked fine for me

**Comment by MikelArnaiz** [comment]
Indeed, it seems zoe [has been deleted from npm](https://www.npmjs.com/package/zoe). cc @jorgegonzalez

**Comment by Albertobar94** [comment]
> You can delete zoe from the devDependencies object in `package.json` and delete the import on `.eslintrc`
> worked fine for me

Did it. researched a bit and so it was just an utility library for eslint and prettier. how did it go for you guys with the project?

**Comment by LitHaxor** [comment]
You can remove "joe" devDependencies

**Comment by Hendrixer** [comment]
thanks all and thanks @AmyShackles for the PR
